### PR TITLE
Fix get_dataPath bug

### PR DESCRIPTION
**Pull request by PiezPiedPy**
Fixes issue #2 

Also fixed intro window not showing sometimes ??

`stockButton is null` log error shows up before MainMenu Scene but stockbutton gets loaded after the log, so changed it to a Warning.

### CODE REVIEW

**Comment by mwerle** [comment]
Eh, @PiezPiedPy, you beat me to it. I -finally- got around to debugging and fixing the errors this mod causes ( which I raised in Issue #1 ) and you now also identified and fixed them :)  I was about to sort out pull requests when I saw you had already done so.

@linuxgurugamer The following are the root causes, it may be worthwhile to keep in mind for other mods; in general there are quite a few things which developers are not allowed to do in MonoBehaviour constructors or instance field initializers. While they may or may not cause  issues when using the release build of the Unity Engine, they certainly cause issues in the Debug build and I wouldn't rely on them working / continuing to work in future versions or on other platforms. Better safe than sorry.

The quotes are directly from the log output of the Debug Unity engine.

> get_dataPath is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead.
> See "Script Serialization" page in the Unity Manual for further details.

get_dataPath is called internally by KSPUtil.ApplicationRootPath.

> GetControlID is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'IntroWindowClass' on game object 'IntroWindowClass'.

References:
* https://blogs.unity3d.com/2016/06/06/serialization-monobehaviour-constructors-and-unity-5-4/
* https://docs.unity3d.com/Manual/script-Serialization.html

**Comment by PiezPiedPy** [comment]
Had to be done, The spam was getting in the way of my debugging sessions with Kerbalism. Thought I might as well post a PR so others could benefit rather than keeping the fix for my own private use.

@linuxgurugamer If you look at the VS branch on my fork you will see a buildscript folder that contains a script for setting up the debug information for Unity. Also I suggest you take a look at the .csproj file, it may have some useful tips for you on how you can build debug and release versions for KSP1.3 and 1.4 by using the config switcher in VS ;)
There is also useful information in the CONTRIBUTING.md file in Kerbalism and Trajectories I put together that will show how you can set up the debugging environment for KSP/Unity. See the Debugging with Visual Studio and Unity section. https://github.com/steamp0rt/Kerbalism/blob/master/CONTRIBUTING.md#debugging-with-visual-studio-and-unity

**Comment by linuxgurugamer** [comment]
Thank you so much, greatly appreciated.
And this is what I love about the community.
One thing, I'll be changing the Log.Warning to a Log.Debug, so that in debug mode the message will be written.

**Comment by PiezPiedPy** [comment]
Glad to help 😉

**Pull request merged**
